dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - nightly

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
  - travis_retry composer install -n

script: ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: nightly
    - env: DEV_DEPENDENCIES

  include:
    - stage: Test
      env: LOWEST_DEPENDENCIES
      install:
        - travis_retry composer update -n --prefer-lowest

    - stage: Test
      env: LOWEST_DEPENDENCIES
      php: 7.2
      install:
        - travis_retry composer update -n --prefer-lowest

    - stage: Test
      env: LOWEST_DEPENDENCIES
      php: nightly
      install:
        - travis_retry composer update -n --prefer-lowest

    - stage: Test
      env: DEV_DEPENDENCIES
      php: nightly
      install:
        - composer config minimum-stability dev
        - travis_retry composer update -n

    - stage: Coding standard
      script:
        - ./vendor/bin/phpcs
