language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
    - DEPENDENCIES=
    - DEPENDENCIES=--prefer-lowest

install:
    composer update --no-interaction --prefer-stable --prefer-dist $DEPENDENCIES

script: make test

stages:
    - Code Quality
    - Test

jobs:
    allow_failures:
        - php: nightly

    include:
        - stage: Code Quality
          name: Lint
          php: 7.1
          script: make lint
        - name: Coding Standard
          php: 7.1
          script: make cs
        - name: Static Analysis
          php: 7.1
          script: make static-analysis
